# Generated by Django 4.2.5 on 2024-02-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_admin', '0003_rename_modified_at_filmwork_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='file_path',
            field=models.TextField(blank=True, null=True, verbose_name='file_path'),
        ),
    ]
